name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Push changes to main
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Commit message"
        git push https://godlysaiko:TOKEN@github.com/godlysaiko/repository.git HEAD:main
      env:
        TOKEN: ${{ secrets.PAT }}
